"""auth_tokens

Revision ID: 85551320403f
Revises: 4f3a6d5c42b5
Create Date: 2023-07-27 16:26:39.500027

"""
from alembic import op
import sqlalchemy as sa

from src.auth.models import TokenChoicesTypes, AuthToken

# revision identifiers, used by Alembic.
revision = '85551320403f'
down_revision = '4f3a6d5c42b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('token', sa.String(length=32), nullable=False),
                    sa.Column('token_type', TokenChoicesTypes(AuthToken.TOKEN_TYPES), nullable=False),
                    sa.Column('token_owner', sa.String(length=150), nullable=False),
                    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.Column('expired', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
