"""socials

Revision ID: e3d6008612e2
Revises: 133cd22d2a93
Create Date: 2023-08-02 21:05:58.342313

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e3d6008612e2'
down_revision = '133cd22d2a93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socials',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('portfolio_info_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=35), nullable=False),
                    sa.Column('link', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['portfolio_info_id'], ['portfolio_info.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('type_writer_info', 'portfolio_info_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('type_writer_info', 'portfolio_info_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.drop_table('socials')
    # ### end Alembic commands ###
